# https://devdocs.prestashop.com/8/modules/concepts/services/
services:
    PrestaShop\Module\DemoProductForm\Form\Modifier\ProductFormModifier:
        class: PrestaShop\Module\DemoProductForm\Form\Modifier\ProductFormModifier
        public: true
        arguments:
            - '@translator'
            - '@form.form_builder_modifier'

    PrestaShop\Module\DemoProductForm\CQRS\CommandHandler\UpdateCustomProductCommandHandler:
        class: PrestaShop\Module\DemoProductForm\CQRS\CommandHandler\UpdateCustomProductCommandHandler
        tags:
            - name: tactician.handler
              command: PrestaShop\Module\DemoProductForm\CQRS\Command\UpdateCustomProductCommand

    PrestaShop\Module\DemoProductForm\CQRS\CommandBuilder\CustomProductCommandsBuilder:
        class: PrestaShop\Module\DemoProductForm\CQRS\CommandBuilder\CustomProductCommandsBuilder
        # This tag is important. Core product command builder finds this builder by the tag
        tags: ['core.product_command_builder']

    PrestaShop\Module\DemoProductForm\Form\Type\CustomTabType:
        class: PrestaShop\Module\DemoProductForm\Form\Type\CustomTabType
        parent: 'form.type.translatable.aware'
        public: true
        tags:
            - { name: form.type }
