demo_configuration_form:
  path: /demosymfonyform/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'PrestaShop\Module\DemoSymfonyForm\Controller\DemoConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminDemoSymfonyForm
    _legacy_link: AdminDemoSymfonyForm